export default  {
        Server: Symbol("Server"),
        Application: Symbol("Application"),
        CardManagerController: Symbol("CardManagerController"),
        CardManagerService: Symbol("CardManagerService"),
        WebsocketManager: Symbol("WebsocketManager"),
        UserManagerService: Symbol("UserManagerService"),
        HighscoreService: Symbol("HighscoreService"),
        HighscoreController: Symbol("HighscoreController"),
        DifferenceCheckerController: Symbol("DifferenceCheckerController"),
        DifferenceCheckerService: Symbol("DifferenceCheckerService"),
        UserController: Symbol("UserController"),
        GameManagerService: Symbol("GameManagerService"),
        SceneManagerController: Symbol("SceneManagerController"),
        SceneManager: Symbol("SceneManager"),
        GameManagerController: Symbol("GameManagerController"),
};
