export default  {
        Server: Symbol("Server"),
        Application: Symbol("Application"),
        CardManagerController: Symbol("CardManagerController"),
        CardManagerService: Symbol("CardManagerService"),
        WebsocketManager: Symbol("WebsocketManager"),
        UserController: Symbol("UserController"),
        UserManagerService: Symbol("UserManagerService"),
        HighscoreService: Symbol("HighscoreService"),
        HighscoreController: Symbol("HighscoreController"),
        DifferenceCheckerController: Symbol("DifferenceCheckerController"),
        DifferenceCheckerService: Symbol("DifferenceCheckerService"),
        HitValidatorService: Symbol("HitValidatorService"),
        HitValidatorController: Symbol("HitValidatorController"),
        GameManager: Symbol("GameManager"),
        GameManagerController: Symbol("GameManagerController"),
        GameManagerService: Symbol("GameManagerService"),
        SceneManagerController: Symbol("SceneManagerController"),
        SceneManager: Symbol("SceneManager"),
        CardOperations: Symbol("CardOperations"),
};
